name: firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  cloud_firestore: 4.8.2
  firebase_storage: 11.2.4
  image_picker: 1.0.0
  file_picker: ^5.2.8
  convex_bottom_bar: ^3.2.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: ^20.4.54
  google_fonts: ^4.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
