// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLdn42tIRgwdbWFW-2s2E35c80opeX3F8',
    appId: '1:450379015882:web:f0b9adfd4a68fd6a2df633',
    messagingSenderId: '450379015882',
    projectId: 'presence-770c4',
    authDomain: 'presence-770c4.firebaseapp.com',
    storageBucket: 'presence-770c4.appspot.com',
    measurementId: 'G-SBNLZW72MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfuOuQnKM4eUs65_oexcrHfo0agJi9vWc',
    appId: '1:450379015882:android:42db178315a116bb2df633',
    messagingSenderId: '450379015882',
    projectId: 'presence-770c4',
    storageBucket: 'presence-770c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84rRVGgZuIyzz3svkD9XnxZg-tj5mrns',
    appId: '1:450379015882:ios:106679b4b30655382df633',
    messagingSenderId: '450379015882',
    projectId: 'presence-770c4',
    storageBucket: 'presence-770c4.appspot.com',
    iosClientId: '450379015882-6pog9rbttmllq75h9runqqn2cqnfbi4t.apps.googleusercontent.com',
    iosBundleId: 'com.presence.firebase',
  );
}
